# Minecraft server plugins
[viaversion]
src.github = "ViaVersion/ViaVersion"
fetch.url = "https://github.com/ViaVersion/ViaVersion/releases/download/$ver/ViaVersion-$ver.jar"

[viabackwards]
src.github = "ViaVersion/ViaBackwards"
fetch.url = "https://github.com/ViaVersion/ViaBackwards/releases/download/$ver/ViaBackwards-$ver.jar"

[gsit]
src.github = "Gecolay/GSit"
fetch.url = "https://github.com/Gecolay/GSit/releases/download/$ver/GSit-$ver.jar"

[lunachat]
src.github = "ucchyocean/LunaChat"
fetch.url = "https://github.com/ucchyocean/LunaChat/releases/download/$ver/LunaChat.jar"

# Zen userscripts
[aki-boost]
src.git = "https://github.com/shapoco/aki-boost.git"
src.branch = "main"
fetch.git = "https://github.com/shapoco/aki-boost.git"

[danime-plus]
src.git = "https://github.com/hamachi25/dAnimePlus.git"
src.branch = "main"
fetch.git = "https://github.com/hamachi25/dAnimePlus.git"

# Others
[codewhale]
src.github = "Hmbown/CodeWhale"
fetch.url = "https://github.com/Hmbown/Codewhale/releases/download/$ver/codewhale-linux-x64"
