{
  config,
  lib,
  pkgs,
  ...
}:

with lib;
let
  cfg = config.my.home.desktop.gaming;
in
{
  options.my.home.desktop.gaming = {
    enable = mkEnableOption "Gaming tools and optimizations";
    nvidiaOffload = {
      enable = mkEnableOption "NVIDIA PRIME offload launchers (requires nvidia-offload on the system)";
    };
  };

  config = mkIf cfg.enable {
    home.packages = with pkgs; [
      mangohud_git
      protonup-qt
      heroic
      prismlauncher
      steam-run
      gamescope_git
    ];

    # `nvidia-offload` is generated by the NixOS nvidia module when PRIME
    # offload is enabled; overriding the stock .desktop entries by file name
    # makes each launcher's default action land on the dGPU.
    # xdg.desktopEntries is broken in this home-manager (the removed
    # `extraConfig` option is still evaluated per entry), so use xdg.dataFile.
    xdg.dataFile = lib.mkIf cfg.nvidiaOffload.enable {
      "applications/steam-nvidia.desktop" = {
        text = ''
          [Desktop Entry]
          Type=Application
          Name=Steam (NVIDIA)
          Comment=Launch Steam on the discrete NVIDIA GPU
          Exec=nvidia-offload steam
          Icon=steam
          Categories=Game;
          Terminal=false
        '';
      };

      # Keeps the stock MimeType/StartupWMClass so modpack file associations
      # and window matching keep working.
      "applications/org.prismlauncher.PrismLauncher.desktop" = {
        text = ''
          [Desktop Entry]
          Version=1.0
          Name=Prism Launcher
          Comment=Discover, manage, and play Minecraft instances
          Type=Application
          Terminal=false
          Exec=nvidia-offload prismlauncher %U
          StartupNotify=true
          Icon=org.prismlauncher.PrismLauncher
          Categories=Game;ActionGame;AdventureGame;Simulation;PackageManager;
          Keywords=game;minecraft;mc;
          StartupWMClass=PrismLauncher
          MimeType=application/zip;application/x-modrinth-modpack+zip;x-scheme-handler/curseforge;x-scheme-handler/prismlauncher;
        '';
      };

      # Same override, so Wine/Proton titles inherit the offload environment.
      "applications/com.heroicgameslauncher.hgl.desktop" = {
        text = ''
          [Desktop Entry]
          Name=Heroic Games Launcher
          Exec=nvidia-offload heroic %u
          Terminal=false
          SingleMainWindow=true
          Type=Application
          Icon=com.heroicgameslauncher.hgl
          StartupWMClass=heroic
          Comment=An Open Source Launcher for GOG, Epic Games and Amazon Games
          MimeType=x-scheme-handler/heroic;
          Categories=Game;
        '';
      };
    };

    home.shellAliases = lib.mkIf cfg.nvidiaOffload.enable {
      steam-nvidia = "nvidia-offload steam";
      prismlauncher-nvidia = "nvidia-offload prismlauncher";
      heroic-nvidia = "nvidia-offload heroic";
    };
  };
}
