# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  aki-boost = {
    pname = "aki-boost";
    version = "ee14b7d53f334fa408cbcf0aaca31ce79546d65b";
    src = fetchgit {
      url = "https://github.com/shapoco/aki-boost.git";
      rev = "ee14b7d53f334fa408cbcf0aaca31ce79546d65b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Kfyiv0t9wj+CNM6i+TtEu/vfLZTZf5WTbzSI9wxSOCM=";
    };
    date = "2025-08-20";
  };
  codewhale = {
    pname = "codewhale";
    version = "v0.10.0";
    src = fetchurl {
      url = "https://github.com/Hmbown/Codewhale/releases/download/v0.10.0/codewhale-linux-x64";
      sha256 = "sha256-xEPCwyx0PdgP9WOXsee7/lWxymMG/1UGW5d7xlXVDtE=";
    };
  };
  danime-plus = {
    pname = "danime-plus";
    version = "43218883d98f2ecec61b803dc19abc83db060858";
    src = fetchgit {
      url = "https://github.com/hamachi25/dAnimePlus.git";
      rev = "43218883d98f2ecec61b803dc19abc83db060858";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-xNFI+SaT/QhyIbNRsFmThydjxfjestyScZXo/bd9lvw=";
    };
    date = "2025-07-12";
  };
  gsit = {
    pname = "gsit";
    version = "3.7.0";
    src = fetchurl {
      url = "https://github.com/Gecolay/GSit/releases/download/3.7.0/GSit-3.7.0.jar";
      sha256 = "sha256-kyFMIy/lNaZFethxHLHgXQ5zCkkc4wPjnjDHb4jdLjA=";
    };
  };
  lunachat = {
    pname = "lunachat";
    version = "v3.0.16";
    src = fetchurl {
      url = "https://github.com/ucchyocean/LunaChat/releases/download/v3.0.16/LunaChat.jar";
      sha256 = "sha256-k9A1ptno5uxcw8+mC9BoB0KWaop6ccS+APgpwjJzM2o=";
    };
  };
  viabackwards = {
    pname = "viabackwards";
    version = "5.12.0";
    src = fetchurl {
      url = "https://github.com/ViaVersion/ViaBackwards/releases/download/5.12.0/ViaBackwards-5.12.0.jar";
      sha256 = "sha256-GU6SUCJGMidNezwX5BHgMakiPBhjxvUTjVPHIfB6t40=";
    };
  };
  viaversion = {
    pname = "viaversion";
    version = "5.12.0";
    src = fetchurl {
      url = "https://github.com/ViaVersion/ViaVersion/releases/download/5.12.0/ViaVersion-5.12.0.jar";
      sha256 = "sha256-csQKanAtZ/Im/JoNitgquhSD/avi5hWbzd2y3AcHULA=";
    };
  };
}
