# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  gsit = {
    pname = "gsit";
    version = "3.6.0";
    src = fetchurl {
      url = "https://github.com/Gecolay/GSit/releases/download/3.6.0/GSit-3.6.0.jar";
      sha256 = "sha256-mvTCLMu7SQFJ9n+H6aRVnxObZaBQKKKTgVfaGgbxmo4=";
    };
  };
  lunachat = {
    pname = "lunachat";
    version = "v3.0.16";
    src = fetchurl {
      url = "https://github.com/ucchyocean/LunaChat/releases/download/v3.0.16/LunaChat.jar";
      sha256 = "sha256-k9A1ptno5uxcw8+mC9BoB0KWaop6ccS+APgpwjJzM2o=";
    };
  };
  viabackwards = {
    pname = "viabackwards";
    version = "5.12.0";
    src = fetchurl {
      url = "https://github.com/ViaVersion/ViaBackwards/releases/download/5.12.0/ViaBackwards-5.12.0.jar";
      sha256 = "sha256-GU6SUCJGMidNezwX5BHgMakiPBhjxvUTjVPHIfB6t40=";
    };
  };
  viaversion = {
    pname = "viaversion";
    version = "5.12.0";
    src = fetchurl {
      url = "https://github.com/ViaVersion/ViaVersion/releases/download/5.12.0/ViaVersion-5.12.0.jar";
      sha256 = "sha256-csQKanAtZ/Im/JoNitgquhSD/avi5hWbzd2y3AcHULA=";
    };
  };
}
