# This file was @generated by nvfetcher, do not edit!
{ fetchurl, ... }:
{
  viaversion = {
    pname = "viaversion";
    version = "5.7.0";
    src = fetchurl {
      url = "https://github.com/ViaVersion/ViaVersion/releases/download/5.7.0/ViaVersion-5.7.0.jar";
      sha256 = "sha256-9qwEGBYqOrUUVTVAOSi4iGCvhhlRkCD39Pebe0/3Yro=";
    };
  };
  viabackwards = {
    pname = "viabackwards";
    version = "5.7.0";
    src = fetchurl {
      url = "https://github.com/ViaVersion/ViaBackwards/releases/download/5.7.0/ViaBackwards-5.7.0.jar";
      sha256 = "sha256-dxN2z1y1Lp6PFPfGJiOERKRE6ZlVUrUSu5lXTfd2aqU=";
    };
  };
}
