# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  gsit = {
    pname = "gsit";
    version = "3.1.1";
    src = fetchurl {
      url = "https://github.com/Gecolay/GSit/releases/download/3.1.1/GSit-3.1.1.jar";
      sha256 = "sha256-fHM05GM5hOzEpfZIZklaAubBJehUwQWaIeib5KHLjwA=";
    };
  };
  lunachat = {
    pname = "lunachat";
    version = "v3.0.16";
    src = fetchurl {
      url = "https://github.com/ucchyocean/LunaChat/releases/download/v3.0.16/LunaChat.jar";
      sha256 = "sha256-k9A1ptno5uxcw8+mC9BoB0KWaop6ccS+APgpwjJzM2o=";
    };
  };
  viabackwards = {
    pname = "viabackwards";
    version = "5.7.0";
    src = fetchurl {
      url = "https://github.com/ViaVersion/ViaBackwards/releases/download/5.7.0/ViaBackwards-5.7.0.jar";
      sha256 = "sha256-dxN2z1y1Lp6PgU9iYoTWS2VI5JmYbnVRUrmV1PdWqjU=";
    };
  };
  viaversion = {
    pname = "viaversion";
    version = "5.7.0";
    src = fetchurl {
      url = "https://github.com/ViaVersion/ViaVersion/releases/download/5.7.0/ViaVersion-5.7.0.jar";
      sha256 = "sha256-9qwEGBYqOrUUVTVAOSi4uGBi9VHGGUAg97G31Pe2K6U=";
    };
  };
}
